# Régression logistique sur le jeu de données test

In [2]:
import numpy as np

import pandas as pd

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

import joblib


In [5]:
jeu_test=pd.read_csv(r"C:\Users\Rénato CATALFAMO\Desktop\billets_production.CSV", sep=',')


In [6]:
# préparation des variables quanti du jeu test

x=jeu_test.drop(columns='id')

In [7]:
# Observation

x

diagonal  height_left  height_right  margin_low  margin_up  length
0    171.76       104.01        103.54        5.21       3.30  111.42
1    171.87       104.17        104.13        6.00       3.31  112.09
2    172.00       104.58        104.29        4.99       3.39  111.57
3    172.49       104.55        104.34        4.44       3.03  113.20
4    171.65       103.63        103.56        3.77       3.16  113.33

In [8]:
lr = joblib.load('lr.joblib')
scaler = joblib.load('std_scale.joblib')

In [9]:
x=scaler.transform(x)

In [10]:
# Prédiction sur le jeu de données test

res=lr.predict(x)
res

array([False, False, False, False,  True])

In [11]:
# probabilité

jeu_test_pro=lr.predict_proba(x)
jeu_test_pro

array([[9.99899546e-01, 1.00453779e-04],
       [9.99999818e-01, 1.81872725e-07],
       [9.99999936e-01, 6.43889809e-08],
       [7.96443158e-01, 2.03556842e-01],
       [1.19585563e-05, 9.99988041e-01]])

In [12]:
jeu_test['resultat']=res

In [13]:
# observatiàn des resultats de prédiction en fonction du modèle

jeu_test

diagonal  height_left  height_right  margin_low  margin_up  length   id  \
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1   
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2   
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3   
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4   
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5   

   resultat  
0     False  
1     False  
2     False  
3     False  
4      True

In [14]:
km = joblib.load('km.joblib')


In [15]:
# k_means prédiction \ donnée numéro 4

km.predict(x)

array([1, 1, 1, 0, 0])

In [16]:
# Code \ Evaluation

In [17]:
jeu_EVALU=pd.read_csv(r"C:\Users\Rénato CATALFAMO\Desktop\ (Nom du fichier)  ", sep=',')
                      
x1=jeu_EVALU.drop(columns='id')
                      
lr_1 = joblib.load('lr.joblib')
scaler_1 = joblib.load('std_scale.joblib')
                      
x1=scaler_1.transform(x1)
                      
# Prédiction sur le jeu de données d'évaluation

res1=lr_1.predict(x1)
res1

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Rénato CATALFAMO\\Desktop\\   '

In [ ]:
jeu_EVALU_pro=lr_1.predict_proba(x1)
jeu_EVALU_pro

In [ ]:
# base evaluation

jeu_EVALU['resultat']=res1

In [ ]:
# prédiction du k_means 

km_1 = joblib.load('km.joblib')
km_1.predict(x1)